services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/api
      SPRING_DATASOURCE_USERNAME: api
      SPRING_DATASOURCE_PASSWORD: api
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres-db
      - redis
    command: ["sh", "-c", "until nc -z -v -w30 postgres-db 5432; do echo 'Waiting for database...'; sleep 1; done; java -jar /app/app.jar"]
    networks:
      - cryptomonnaie-network

  postgres-db:
    image: postgres:15
    container_name: postgres-data-db
    hostname: postgres-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - cryptomonnaie-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - cryptomonnaie-network

volumes:
  postgres_data_db:

networks:
  cryptomonnaie-network:
    driver: bridge
